import LoginProviders from "@/components/auth/login-providers";
import RegisterForm from "@/components/auth/register-form";

export const metadata = {
  title: "Registrarse",
  description: "Generated by create next app",
  icon: ""
};

export default function RegisterPage() {
  return (
    <main className="flex flex-col justify-center items-center w-full min-h-screen p-6 mx-auto">
      <h1 className="text-3xl text-center font-bold">Regístrate</h1>
      <div className="flex justify-start items-center gap-12 w-full max-w-5xl mt-10 p-10 mx-auto">
        <RegisterForm />
        <div className="flex flex-col items-center justify-center gap-4 w-[4px] h-full text-gray-400 py-2">
          <hr className="h-full w-[1px] bg-gray-400" />
          <span>o</span>
          <hr className="h-full w-[1px] bg-gray-400" />
        </div>
        <div className="flex flex-col items-center justify-center w-full gap-4">
          <LoginProviders />
        </div>
      </div>
    </main>
  )
}
