
import Link from "next/link";

import LoginProviders from "@/components/auth/login-providers";
import LoginFormHandler from "@/components/auth/login/login-form-handler";

export const metadata = {
  title: "Kazu Moda | Ingresar",
  description: "Generated by create next app",
  keywords: ["ropa", "moda"],
};

export default function LoginPage() {
  return (
    <main className="flex flex-col justify-center items-center w-full h-screen p-6 mx-auto">
      <h1 className="text-3xl text-center font-bold">Inicia Sesión</h1>
      <div className="flex justify-start items-center gap-12 w-full max-w-5xl mt-10 p-10 mx-auto">
        <LoginFormHandler />
        <div className="flex flex-col items-center justify-center gap-4 w-[4px] h-full text-gray-400 py-2">
          <hr className="h-full w-[1px] bg-gray-400" />
          <span>o</span>
          <hr className="h-full w-[1px] bg-gray-400" />
        </div>
        <div className="flex flex-col items-center justify-start w-full gap-4">
          <LoginProviders />
        </div>
      </div>
      <p className="mt-10">
        ¿No tienes una cuenta? <Link href="/registro" className="text-blue-600 hover:underline">Regístrate aquí</Link>
      </p>
    </main>
  );
}
